CREATE TABLE `newTable`(
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    enable BOOLEAN DEFAULT TRUE,
    birthdate DATETIME
)